-- DROP INSTRUCTIONS
SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

DROP DATABASE eclihand;

CREATE DATABASE eclihand WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'French_France.1252' LC_CTYPE = 'French_France.1252';
ALTER DATABASE eclihand OWNER TO postgres;

\connect eclihand

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

ALTER SCHEMA public OWNER TO postgres;
COMMENT ON SCHEMA public IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';

SET search_path = public, pg_catalog;
SET default_tablespace = '';
SET default_with_oids = false;

--CREATE INSTRUCTIONS
CREATE SEQUENCE OBJ_OBJECT_ID_SEQ;

CREATE TABLE OBJ_OBJECT (
ID INTEGER NOT NULL,
OBJ_INDEX TEXT,
CONSTRAINT PK_OBJ PRIMARY KEY (ID)
);

CREATE TABLE ILL_ILLUSTRABLE (
ID INTEGER NOT NULL,
CONSTRAINT PK_ILL PRIMARY KEY (ID),
CONSTRAINT FK_ILL__OBJ FOREIGN KEY (ID) REFERENCES OBJ_OBJECT (ID)
);

CREATE TABLE PER_PERSON (
ID INTEGER NOT NULL,
PER_FIRST_NAME VARCHAR(64) NOT NULL,
PER_LAST_NAME VARCHAR(64) NOT NULL,
PER_BIRTH_DATE DATE,
PER_GENDER VARCHAR(64),
CONSTRAINT PK_PER PRIMARY KEY (ID),
CONSTRAINT FK_PER__ILL FOREIGN KEY (ID) REFERENCES ILL_ILLUSTRABLE (ID)
);

CREATE TABLE PLA_PLAYER (
ID INTEGER NOT NULL,
PLA_PER_ID INTEGER NOT NULL,
CONSTRAINT PK_PLA PRIMARY KEY (ID),
CONSTRAINT FK_PLA__PER FOREIGN KEY (PLA_PER_ID) REFERENCES PER_PERSON (ID),
CONSTRAINT FK_PLA__ILL FOREIGN KEY (ID) REFERENCES ILL_ILLUSTRABLE (ID)
);

CREATE TABLE TEA_TEAM (
ID INTEGER NOT NULL,
TEA_YEAR INTEGER NOT NULL,
TEA_GENDER VARCHAR(64) NOT NULL,
CONSTRAINT PK_TEA PRIMARY KEY (ID),
CONSTRAINT FK_TEA__ILL FOREIGN KEY (ID) REFERENCES ILL_ILLUSTRABLE (ID)
);

CREATE TABLE AFF_PLAYER_TEAM_AFFILIATION (
AFF_PLA_ID INTEGER NOT NULL,
AFF_TEA_ID INTEGER NOT NULL,
CONSTRAINT PK_AFF PRIMARY KEY (AFF_PLA_ID,AFF_TEA_ID),
CONSTRAINT FK_AFF__PLA FOREIGN KEY (AFF_PLA_ID) REFERENCES PLA_PLAYER (ID),
CONSTRAINT FK_AFF__TEA FOREIGN KEY (AFF_TEA_ID) REFERENCES TEA_TEAM (ID)
);