DELETE FROM AFF_PLAYER_TEAM_AFFILIATION;
DELETE FROM TEA_TEAM;
DELETE FROM PLA_PLAYER;
DELETE FROM PER_PERSON;

INSERT INTO PER_PERSON VALUES (1,'Mathieu','Pedrero','1986-06-23','MASC');
INSERT INTO PER_PERSON VALUES (2,'Thomas','Oursel','1986-12-11','MASC');
INSERT INTO PER_PERSON VALUES (3,'Jean-Baptiste','Zigrand','1986-06-02','MASC');
INSERT INTO PER_PERSON VALUES (4,'Gwennino','Gomes','1988-09-23','MASC');
INSERT INTO PER_PERSON VALUES (5,'Laure','Alliès','1986-06-23','FEM');
INSERT INTO PER_PERSON VALUES (6,'Marion','Picard','1986-12-11','FEM');

INSERT INTO PLA_PLAYER VALUES (1,1);
INSERT INTO PLA_PLAYER VALUES (2,2);
INSERT INTO PLA_PLAYER VALUES (3,3);
INSERT INTO PLA_PLAYER VALUES (4,4);
INSERT INTO PLA_PLAYER VALUES (5,5);
INSERT INTO PLA_PLAYER VALUES (6,6);

INSERT INTO TEA_TEAM VALUES (1,2012,'MASC');
INSERT INTO TEA_TEAM VALUES (2,2011,'MASC');
INSERT INTO TEA_TEAM VALUES (3,2010,'MASC');
INSERT INTO TEA_TEAM VALUES (4,2009,'MASC');
INSERT INTO TEA_TEAM VALUES (5,2008,'MASC');
INSERT INTO TEA_TEAM VALUES (6,2012,'FEM');
INSERT INTO TEA_TEAM VALUES (7,2011,'FEM');
INSERT INTO TEA_TEAM VALUES (8,2010,'FEM');
INSERT INTO TEA_TEAM VALUES (9,2009,'FEM');
INSERT INTO TEA_TEAM VALUES (10,2008,'FEM');

INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (1,3);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (1,4);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (1,5);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (2,2);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (2,3);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (2,4);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (2,5);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (3,3);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (3,4);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (3,5);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (4,2);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (4,3);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (4,4);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (5,8);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (5,9);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (5,10);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (6,7);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (6,8);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (6,9);
INSERT INTO AFF_PLAYER_TEAM_AFFILIATION VALUES (6,10);


commit;